const Images = {
  BackgroundImage: require('./background.png'),
  PublicBackgroundImage: require('./public-background.png'),
  LogoImage: require('./logo.png'),
  SplashScreenLogo: require('./logo-color-splash.png'),
  ArticlesImage: require('./articles.png'),
  VideosImage: require('./videos.png'),
  FoodListImage: require('./food-list.png'),
  FoodVideosImage: require('./food-videos.png'),
  RecipesImage: require('./recipes.png'),
  MyHealthRecordImage: require('./my-health-record.png'),
  MyLifestyleTrackerImage: require('./my-lifestyle-tracker.png'),
  ContentGalleryImage: require('./content-gallery.png'),
  FoodIsMedicineImage: require('./food-is-medicine.png'),
  MyWellnessJourneyImage: require('./my-wellness-journey.png'),
};

export const {
  BackgroundImage,
  PublicBackgroundImage,
  LogoImage,
  SplashScreenLogo,
  ArticlesImage,
  VideosImage,
  FoodListImage,
  FoodVideosImage,
  RecipesImage,
  MyHealthRecordImage,
  MyLifestyleTrackerImage,
  ContentGalleryImage,
  FoodIsMedicineImage,
  MyWellnessJourneyImage,
} = Images;
