const PERSONAL_INFORMATION = 'PERSONAL_INFORMATION';
const CONDITIONS = 'CONDITIONS';
const TELL_ABOUT_HEALTH = 'TELL_ABOUT_HEALTH';
const ANSWER_MORE_QUESTIONS = 'ANSWER_MORE_QUESTIONS';
const NEXT_DOCTORS_APPOINTMENT = 'NEXT_DOCTORS_APPOINTMENT';
const TELL_ABOUT_LIFESTYLE = 'TELL_ABOUT_LIFESTYLE';
const SCREENING_TEST = 'SCREENING_TEST';
const PAP_SMEAR = 'PAP_SMEAR';
const MAMMOGRAM = 'MAMMOGRAM';
const CONGRATULATIONS = 'CONGRATULATIONS';

const STEPS_HISTORY = [
  PERSONAL_INFORMATION,
  CONDITIONS,
  TELL_ABOUT_HEALTH,
  ANSWER_MORE_QUESTIONS,
  NEXT_DOCTORS_APPOINTMENT,
  TELL_ABOUT_LIFESTYLE,
  SCREENING_TEST,
  PAP_SMEAR,
  MAMMOGRAM,
  CONGRATULATIONS,
] as const;

export const STEPS = STEPS_HISTORY.reduce(
  (map, step, index) => ({
    ...map,
    [step]: index,
  }),
  {} as Record<typeof STEPS_HISTORY[number], number>,
);

export const STEP_KEY = {
  [STEPS.PERSONAL_INFORMATION]: 'personalInformation',
  [STEPS.CONDITIONS]: 'conditions',
  [STEPS.TELL_ABOUT_HEALTH]: 'info',
  [STEPS.ANSWER_MORE_QUESTIONS]: 'questions',
  [STEPS.NEXT_DOCTORS_APPOINTMENT]: 'appointments',
  [STEPS.TELL_ABOUT_LIFESTYLE]: 'lifestyle',
  [STEPS.SCREENING_TEST]: 'colon',
  [STEPS.PAP_SMEAR]: 'papSmear',
  [STEPS.MAMMOGRAM]: 'mammogram',
  [STEPS.CONGRATULATIONS]: 'congratulations',
} as const;

export const AGE_45 = 45;

const RECURRENCE_PAP_SMEAR = 'papSmear';
const RECURRENCE_BLOOD_STOOL = 'bloodStoolTesting';
const RECURRENCE_COLOGUARD = 'cologuard';
const RECURRENCE_COLONOSCOPY = 'colonoscopy';
const RECURRENCE_COLONOGRAPHY = 'colonography';
const RECURRENCE_MAMMOGRAM = 'mammogram';

export const RECURRENCES = {
  PAP_SMEAR: RECURRENCE_PAP_SMEAR,
  BLOOD_STOOL: RECURRENCE_BLOOD_STOOL,
  COLONOGUARD: RECURRENCE_COLOGUARD,
  COLONOSCOPY: RECURRENCE_COLONOSCOPY,
  COLONOGRAPHY: RECURRENCE_COLONOGRAPHY,
  MAMMOGRAM: RECURRENCE_MAMMOGRAM,
};

export const FEMALE = 'Female';
export const MALE = 'Male';

export const GENDER = {
  FEMALE,
  MALE,
};
